### ISSUE TITLE
Failed to query. Error message:  timed out

### ISSUE THREAD

**Issue by d2nekomet** [w-gao/py-mcpe-query#1]
Why?
My code:

from py_mcpe_query.query import Query
from textblob import TextBlob

host = input('Введите IP сервера: ')
port = input('Введите Port сервера: ')
lang = TextBlob(host)

def query():
	if lang.detect_language() == 'en':
		q = Query(str(host), int(port))	
		server_data = q.query()
		if len(server_data.HOSTNAME) <= 15:
			infoq = 'IP:Port - ' + str(host) + ':' + str(port) + '\nНазвание: '+ str(server_data.HOSTNAME)		
			print('\n\n'+ str(q))
query()

**Comment by d2nekomet** [comment]
Да ответь же ты сука

**Comment by w-gao** [comment]
This should be fixed in version 0.2.1.  Please reopen if issue persist.
