### ISSUE TITLE
pypi outdated

### ISSUE THREAD

**Issue by rjworks** [w-gao/py-mcpe-query#2]
ERROR: Could not find a version that satisfies the requirement py_mcpe_query
ERROR: No matching distribution found for py_mcpe_query

**Comment by w-gao** [comment]
Thank you for bringing this to my attention! I'll make sure to find a fix asap.

**Comment by w-gao** [comment]
@rjworks Please test with version 0.2.1.  I was not able to reproduce this problem, but I've bumped the version to fix the other issue.

**Comment by w-gao** [comment]
Stale. Please reopen if you are still having this problem.
